[package]
name = "rotapong"
version = "0.1.0"
authors = ["wrazik <wojciech.razik@gmail.com>"]

[dependencies]
rand = "0.5.5"
piston = "0.37.0"
pistoncore-glutin_window = "0.47.0"
piston2d-opengl_graphics = "0.53.0"
piston2d-graphics = "0.26.0"
clap = "2.32.0"